name: deploy-on-different-environments

on:
    workflow_dispatch:
    push:
        branches:
            - main
    release:
        types: [prereleased]

env:
    ENV_IN_FILE: "this is from the GA file!"
jobs:
    deploy-to-environment-A:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        environment: dev
            
        steps:
            - name: Deploy to Environment A
              env:
                  STEP_ENV_VAR: "This is from step A"
              run: |
                echo "$ENV_IN_FILE \n $STEP_ENV_VAR \n $MESSAGE"
    
    deploy-to-environment-B:
        if: github.event_name == 'release' && github.event.release.prerelease == true
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Deploy to Environment B
              env:
                  STEP_ENV_VAR: "This is from step B"
              run: |
                echo "$ENV_IN_FILE \n $STEP_ENV_VAR \n $MESSAGE"
